### ISSUE TITLE
new bumper scheduling

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/experimental#4]
ashton
can you make sure that you update the excel spread sheet- isnt that what we
agreed ? to track the new bumpers on the excel spraed sheet
anyway discuss with corey and josephine

can you tell me when the first new bumper will go up ?

roger

**Comment by amb141330** [comment]
First bumper should go up on 5/30/15. This will be completed by @coreysmart92  for The Bold Roast. Will figure out a good format to add to the excel sheet once we have decided on stingers for the month of June.

**Comment by cassininazir** [comment]
Please also make sure that it appears on the Experimental Website and Soundcloud as well.

**Comment by rmalina** [comment]
please work with the new channel producers of RAMI to develop a bumper/stinger with them-this is culturally sensitive so important to collaborate with them
roger
@coreysmart92 @cassininazir

**Comment by cassininazir** [comment]
This issue was moved to creativedisturbance/podcasts#111
