### ISSUE TITLE
Confirm Access to Experimental Space on Creative Disturbance

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/experimental#5]
@amb141330 I've added you as a user to the Experimental space. You should have received an email with your username and password. 

Confirm that you can login and then close this task.

**Comment by amb141330** [comment]
I have not received an email with the account information. I checked all folders for anything containing wordpress or experimental and haven't seen anything.

**Comment by amb141330** [comment]
Still no email to this space with login information. Any updates?

**Comment by cassininazir** [comment]
Login at http://x.creativedisturbance.org/wp-admin with the username and password we discussed.

**Comment by amb141330** [comment]
Logged in successfully.
