### ISSUE TITLE
New Bumpers

### ISSUE THREAD

**Issue by amb141330** [creativedisturbance/experimental#6]
Put the new bumpers on the experimental page.

**Comment by cassininazir** [comment]
New bumpers are located in [CD 2.2.1.5] (https://drive.google.com/drive/folders/0B0RS2YDJUln1fng5aTlnd0tzTXVZamZOeUdHckN0OEJ4RXVDZVFITHlHOTJ4bzdrdjZNNHc). There are four there.

**Comment by cassininazir** [comment]
This issue was moved to creativedisturbance/podcasts#110
